# Define colors for each AIS level (1-6)
COLOR_MAP = {
    1: '#A8E6CF',
    2: '#FFD3B6',
    3: '#FFB347',
    4: '#F08D5B',
    5: '#882827',
    6: '#878787',
}

# Define groups: how SVG path IDs map to logical body part groups
region_groups = {
    'head': ['Head', 'head_b'],
    'face': ['face', 'left_ear', 'right_ear'],
    'neck': ['neck', 'neck_b_r', 'neck_b_l'],
    'cervical_spine': ['cervical_spine'],
    'shoulder_left': ['shoulder_l',  'shoulder_b_left'],
    'shoulder_right': ['shoulder_r', 'shoulder_b_right'],
    'arm_left': ['arm_l', 'arm_b_left'],
    'arm_right': ['arm_r', 'arm_b_right'],
    'elbow_left': ['elbow_l', 'elbow_b_left'],
    'elbow_right': ['elbow_r', 'elbow_b_right'],
    'forearm_left': ['forearm_l', 'forearm_b_left'],
    'forearm_right': ['forearm_r', 'forearm_b_right'],
    'wrist_left': ['wrist_l', 'wrist_b_left'],
    'wrist_right': ['wrist_r', 'wrist_b_right'],
    'hand_left': ['hand_l', 'hand_b_left'],
    'hand_right': ['hand_r', 'hand_b_right'],
    'chest_left': ['chest_l', 'chest_b_left'],
    'chest_right': ['chest_r', 'chest_b_right'],
    'sternum': ['sternum'],
    'thoracic_spine': ['thoracic_spine'],
    'pelvis_left': ['pelvis_left', 'pelvis_b_left'],
    'pelvis_right': ['pelvis_right', 'pelvis_b_right'],
    'abdomen': ['abdomen'],
    'groin': ['groin'],
    'lumbar_spine': ['lumbar_spine'],
    'back': ['back_b_left', 'back_b_right'],
    'thigh_left': ['thigh_left', 'thigh_b_left'],
    'thigh_right': ['thigh_right', 'thigh_b_right'],
    'knee_left': ['knee_left', 'knee_b_left'],
    'knee_right': ['knee_right', 'knee_b_right'],
    'calf_left': ['calf_left', 'calf_b_left'],
    'calf_right': ['calf_right', 'calf_b_right'],
    'ankle_left': ['ankle_left', 'ankle_b_left'],
    'ankle_right': ['ankle_right', 'ankle_b_right'],
    'feet_left': ['feet_left', 'feet_b_left'],
    'feet_right': ['feet_right', 'feet_b_right'],
}
